# System

language: bash
git:
  depth: false
addons:
  apt:
    update: true
  homebrew:
    packages:
      - pyenv
os:
  - osx
  - windows
  - linux
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@" # Should test the latest
    - JDK="adopt-openj9@"


# Utilities

_deploy_base: &deploy_base
  provider: releases
  edge: true
  file:
    - "${TRAVIS_BUILD_DIR}/*.tar.gz"
    - "${TRAVIS_BUILD_DIR}/charts/*.pdf"
_repo_filter: &repo_filter
  repo: DanySK/Experiment-2019-FGCS-Self-Integration
_auto_tag: &auto_tag >
    git describe --tags --exact-match HEAD
    || (TAGNAME=$(git describe) && git tag $TAGNAME)
    || git tag "0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%m%S' --format=%cd)"

# Process

stages:
  - name: test
    if: type = cron OR tag is blank AND NOT commit_message =~ /\[AUTOMATIC.*\].*/
  - name: charts
jobs:
  include:
    - stage: charts
      os: linux
      install:
        - curl "${GRAVIS}.install-python.sh" | bash
        - pip install --upgrade pip
        - pip install -r requirements.txt
      script: travis_wait python process.py
      before_deploy:
        - tar -czvf "charts.tar.gz" $TRAVIS_BUILD_DIR/charts/
        - git config --local user.name "Danilo Pianini"
        - git config --local user.email "danilo.pianini@unibo.it"
        - *auto_tag
      deploy:
       - <<: *deploy_base
         on:
           <<: *repo_filter
           tags: false
       - <<: *deploy_base
         on:
           <<: *repo_filter
           tags: true


# Common

before_install: true
install:
  - travis_retry curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - travis_retry source .install-jdk-travis.sh
script:
  - travis_retry ./gradlew clean showAll --parallel
before_cache:
  - travis_retry curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - travis_retry bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.pyenv
