language: bash
git:
  depth: false
addons:
  apt:
    update: true
  homebrew:
    packages:
      - pyenv
os:
  - osx
  - windows
  - linux
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
  matrix:
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@" # Should test the latest
    - JDK="adopt-openj9@"
stages:
  - test
  - charts
jobs:
  include:
    - stage: charts
      os: linux
      install:
        - curl "${GRAVIS}.install-python.sh" | bash
        - pip install --upgrade pip
        - pip install -r requirements.txt
      script: travis_wait python process.py
before_install:
  # Print IP address if possible, so to provide data in case of Maven Central 403
  # See: https://issues.sonatype.org/browse/MVNCENTRAL-4985
  - (ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1') || true
install:
  - travis_retry curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - travis_retry source .install-jdk-travis.sh
script:
  - travis_retry ./gradlew clean showAll --parallel
before_cache:
  - travis_retry curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - travis_retry bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.pyenv
